# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5002de8546f51a90cdd80b832ebf170be84e5e72515ec344a502f810f3278d0a9ba6d8c1cdecc330c3f416f5feb62a9fdec2368a56ecf1632cc30057f8d7f950

test:
  secret_key_base: 4ce88355f9e460a8ce1de3d6fa5f68aafa1185b86d2feb1d2e71312fc7cbfaddf320bfd752bf33486fddb1d8d69f48a706c4e479b8f56e4b8ffa26d1ae13d408

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
